# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - hellowworldwebsite

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://helloworldwebsite.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_126b1fdbbafd4b6daba8b88741660d67 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_480ce3e8a44c40e18f087c7d5c8164e4 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: helloworldwebsite.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_126b1fdbbafd4b6daba8b88741660d67 }}/hello-world:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'hellowworldwebsite'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_84f9f410a146428fa26e3e6244d1d75b }}
        images: 'helloworldwebsite.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_126b1fdbbafd4b6daba8b88741660d67 }}/hello-world:${{ github.sha }}'